### ISSUE TITLE
BusFault error

### ISSUE THREAD

**Issue by bHub** [vad7/nrf24scan#2]
When the app is started with the configuration attached , and during the scan the down arrow is pressed on the pad , flipper crashes with BusFault error.
![flpr-2023-06-09-091947](https://github.com/vad7/nrf24scan/assets/4335699/b82db5af-2023-4952-a64b-15a87b3eda7a)
![flpr-2023-06-09-091833](https://github.com/vad7/nrf24scan/assets/4335699/6d64a8e1-3afa-4f08-b10f-51506ca646bb)

**Comment by vad7** [comment]
fixed

**Comment by bHub** [comment]
I close even if I did not tested the new release. I'm going to wait until this new version will be implemented in Xtreme firmware.
